services:
  db:
    image: postgres:16
    container_name: backend_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: seth_valou
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_autorefill
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data: